### ISSUE TITLE
don't work in environment supports native Promise.allSettlted

### ISSUE THREAD

**Issue by KoharaKazuya** [ungap/promise-all-settled#1]
## Environment

- Node: v12.12.0
- @ungap/promise-all-settled: v0.1.1

## Steps

```javascript
const allSettled = require("@ungap/promise-all-settled");

// error
allSettled([]).catch(err => {
  console.error(err);
  process.exit(1);
});

// no error
allSettled.call(Promise, []).catch(err => {
  console.error(err);
  process.exit(1);
});
```

Output:

```
/Users/kohara/Downloads/promise-all-settled-bind/main.js:3
allSettled([]).catch(err => {
^

TypeError: Promise.all called on non-object
    at allSettled (<anonymous>)
    at Object.<anonymous> (/Users/kohara/Downloads/promise-all-settled-bind/main.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
```

I like ungap project becase we can use the modern features in the same way. I would be happy to use it without any special workaround.

**Comment by WebReflection** [comment]
To be honest, `allSettled` is meant to work as method, so that `call` would be needed when this module becomes vaporware.

What you need to do, is simply require this module as such:

```js
const allSettled = require("@ungap/promise-all-settled").bind(Promise);
```

The ability to make any `@ungap` module vaporwhare, [described here](https://ungap.github.io/#pluginstoremoveunnecessarybloat), doesn't really allow me to auto bind the export, if available, so since the workaround for all native/not-native cases is trivial, do you think it's worth needing to change the current behavior?

**Comment by WebReflection** [comment]
P.S. another approach to keep it vaporware is to normalize the polyfill, or simply write this:

```js
const allSettled = require("@ungap/promise-all-settled");
if (!Promise.allSettled)
  Promise.allSettled = allSettled;
```

The reason the method should not be returned bound, is that it should be compatible with extends of `Promise`. If I bind it to `Promise` itself, it becomes less portable across classes.

Accordingly, I think this module is better off with enforced context, instead of a loosy one.

**Comment by WebReflection** [comment]
So, I've bumped the version as major, due possible braking changes, and improved the README describing how to use this module.

Thanks for filing this though, I should've thought about this before.

**Comment by KoharaKazuya** [comment]
I got that it shouldn't be bound to `Promise` by default. I will use workaround.

Thank you for your new documentation. It prevents users from having problem like me.
